# Generated by Django 3.0.2 on 2020-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgct_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
