# Generated by Django 3.0.2 on 2020-02-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgct_app', '0002_auto_20200203_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
